### PR TITLE
Nick devel

### PR DESCRIPTION
**Pull request by nickcharron**
most of these are formatting changes. I added a .clang_format file to make the format consistent with the rest of our code. So I went through all files and redid the clang format.

Most changes are in the test file and utils. Just added functions to remove the path hardcoding
Also updated the CMakeLists, no point in a cmakelists for the test folder. 

Couple more comments: 
- add includes to the header file only if it's needed in the header. If a class is only used in the cpp file, then only add the include there. That saves compile time significantly
- includes should be ordered like this:
  1. if you have a cpp file with its associated .h file, then the first include should be that .h file
  2. space
  3. all std includes (e.g. #include <vector>)
  4. space
  5. all third party include (e.g., pcl, boost, ...)
  6. space
  7. all includes specific to this codebase (cad_image_markup)

  Each section of includes are then sorted alphabetically, which is done automatically with clang format
- Clean up the data folder in cad_image_markup/data: this will be a good place to include real test data, so we can have a wiki showing people how to run the exectuable on example data. But for now, if this data is used in the unit test only, then keep it only in the unit test data subfolder

### CODE REVIEW

**Comment by nickcharron** [comment]
Feel free to merge whenever. I'd also suggest merging your branch to master. If it's mostly you working on it, you can work on the master. 

I like to use branches for specific features. But if you're just doing general cleanup and testing then you can just use master. Also, remove the other branch if it's no longer useful. Also remove any branches that have been merged to master

**Comment by nickcharron** [comment]
@cchaas-uwaterloo I submitted this PR a while ago, it may be all obsolete now. But can you deal with this? Check the changes, and you might have to manually apply them because there will probably be too many conflicts by now to merge directly. once you've added the relevant changes, close this PR

**Comment by cchaas-uwaterloo** [comment]
Hey yeah, I'm sorry I lost track of this. There's been a ton of changes since then so I'll go through and address what still seems relevant manually. Restructuring the includes and the CMakeLists at least is definitely overdue.

**Comment by cchaas-uwaterloo** [comment]
Incorporated the changes into my branch.

**Pull request closed without merging**
